platform :ios, '16.0'

ENV['COCOAPODS_DISABLE_STATS'] = '1'

flutter_root = ENV['FLUTTER_ROOT'] || File.expand_path('~/flutter')
require_relative "#{flutter_root}/packages/flutter_tools/bin/podhelper"

target 'Runner' do
  use_frameworks! :linkage => :static
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
    end
  end
end